#ifndef MOUSE_INPUT_H
#define MOUSE_INPUT_H

#include <SDL2/SDL_mouse.h>

enum MouseButton {
	MOUSE_BUTTON_LEFT = SDL_BUTTON_LEFT,
	MOUSE_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
	MOUSE_BUTTON_RIGHT = SDL_BUTTON_RIGHT
};

#endif
